Task 10 completed
AlexandarPetsoranski/SelniumTrainingRepo pull request #1
Opened 2021-10-28 14:03 UTC by AlexandarPetsoranski

In this PR: 

**Following requirements are met:** 
- Develop unit tests for JsonParser class (one of them should be Exception test with >= 5 datasets). Determine by yourself, how many tests should be developed
- Develop 1 test for RealItem class
- Develop 1 test for VirtualItem class
- Develop 2 tests for Cart class
- Disable one of tests from point 1
- Add grouped assertion for one of tests

2021-10-28 18:27 UTC, EugenBorisik requested changes
Common comment:
Please read article https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80
And try to write tests in the same manner. You will see how it will be easier to read and maintain tests

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/VirtualItemTest.java
> +public class VirtualItemTest extends BaseSpec{
Virtual item class is designed as simple model class without any business logic. Such classes don't need tests at all. This point from task has 2 correct resolutions:
1. Do not write tests at all :)
2. Write single test for toString() method, because class overrides it

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/RealItemTest.java
> +public class RealItemTest extends BaseSpec{
Real item class is designed as simple model class without any business logic. Such classes don't need tests at all. This point from task has 2 correct resolutions:
1. Do not write tests at all :)
2. Write single test for toString() method, because class overrides it

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/testData/TestData.java
> +    public static Cart testCart = new Cart("test-cart");
Generate unique random cart name

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/testData/TestData.java
> +    public static Cart createTestCart(String cartName){
Parameter is not used

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/testData/TestData.java
> +        testRealItem.setWeight(1560.0);
You can re-use your createRealItem() method here

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/testData/TestData.java
> +        testVirtualItem.setSizeOnDisk(20000.0);
You can re-use your createVirtualItem() method here

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/testData/TestData.java
> +    public static VirtualItem testVirtualItem = new VirtualItem();
I think you don't need these fields, make them as local variables in your create* methods.

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/BaseSpec.java
> +        System.out.println("Tests passed successfully");
Some tests can fail due to bugs, but your message looks like they will be passing every time. It makes sense to rename in something like "Test execution finished successfully"

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        );    }
Move "}" to new line

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +    void givenMultipleAssertion_whenAssertingAll_thenOK() {
Do not use "_" in java classes/methods/variables names

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        Cart cart = new Cart("TestCart1");
Generate unique random cart name

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +public class CartTest extends BaseSpec{
Add one more test on delete operation

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        List<RealItem> actualRealItems = cart.getRealItems();
According to task description, you can't change initial code.
You can use showItems() method to check items. I understand that it is inconvenient, but it is done specially. This method returns void, that's you need to handle System.out and get this data in string value and then parse this string.

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/JsonParserTests.java
> +    void passWrongFileToReadFromFile_NoSuchFileExceptionPresented(){
Make this test parametrized with >= 5 datasets

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/JsonParserTests.java
> +    void writeToFile_successfullyCreatesJsonFile() throws IOException {
I really like, that you read actual file using your custom code in test on "write" operation. That's great!

Right now you are hard-coding expected result. How should look this test:
- Create test cart with items with random unique name (this cart is your expected result)
- Write this cart in file using JsonParser
- Read your cart using your custom code (you can't read with JsonParser here, because you can miss bug - you've already did this) and map it to Cart object (this cart is your actual result)
- Finally compare 2 Cart objects (I allow you to add some code in Cart/items classes, if you know what to add or just convert them in json values and compare them)

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/JsonParserTests.java
> +        //overriding equals method
Not easier :) Tasks will have such "traps", if you understand how to compare 2 objects of the same class -> I allow you to add this code

2021-10-28 18:27 UTC, EugenBorisik commented on src/test/java/JsonParserTests.java
> +    void readFromFile_InformationProperlyRead() throws IOException {
Could you please use information from comment for "write" test and adjust this test too.

2021-11-01 07:47 UTC, AlexandarPetsoranski commented on src/test/java/VirtualItemTest.java
> +public class VirtualItemTest extends BaseSpec{
I have created tests for toString method

2021-11-01 07:47 UTC, AlexandarPetsoranski commented on src/test/java/RealItemTest.java
> +public class RealItemTest extends BaseSpec{
I have created tests for toString method

2021-11-01 07:59 UTC, AlexandarPetsoranski commented on src/test/java/testData/TestData.java
> +    public static Cart testCart = new Cart("test-cart");
I have created a method generateRandomString but if I pass it as a parameter in Cart constructor this String will be different every single execution. So how can I assert the name of the cart ?

2021-11-01 08:05 UTC, AlexandarPetsoranski commented on src/test/java/testData/TestData.java
> +    public static Cart createTestCart(String cartName){
removed

2021-11-01 08:07 UTC, AlexandarPetsoranski commented on src/test/java/testData/TestData.java
> +        testRealItem.setWeight(1560.0);
Would you please clarify a little bit because I do not understand that ? :)

2021-11-01 08:08 UTC, AlexandarPetsoranski commented on src/test/java/testData/TestData.java
> +    public static VirtualItem testVirtualItem = new VirtualItem();
DONE

2021-11-01 08:09 UTC, AlexandarPetsoranski commented on src/test/java/CartTest.java
> +        );    }
done

2021-11-01 08:10 UTC, AlexandarPetsoranski commented on src/test/java/CartTest.java
> +    void givenMultipleAssertion_whenAssertingAll_thenOK() {
https://dzone.com/articles/7-popular-unit-test-naming 
Which one of these is best to use ?

2021-11-01 08:21 UTC, AlexandarPetsoranski commented on src/test/java/testData/TestData.java
> +        testVirtualItem.setSizeOnDisk(20000.0);
Would you please clarify a little bit because I do not understand that ? :)

2021-11-01 08:49 UTC, AlexandarPetsoranski commented on src/test/java/CartTest.java
> +public class CartTest extends BaseSpec{
DONE

2021-11-01 09:38 UTC, AlexandarPetsoranski commented on src/test/java/JsonParserTests.java
> +    void passWrongFileToReadFromFile_NoSuchFileExceptionPresented(){
DONE

2021-11-01 11:42 UTC, AlexandarPetsoranski commented on src/test/java/JsonParserTests.java
> +    void writeToFile_successfullyCreatesJsonFile() throws IOException {
Both tests for read and write changed

2021-11-01 14:17 UTC, AlexandarPetsoranski commented on src/test/java/CartTest.java
> +        Cart cart = new Cart("TestCart1");
If I do so, how to assert something that would change on every run ?

2021-11-01 14:30 UTC, AlexandarPetsoranski commented on src/test/java/CartTest.java
> +        List<RealItem> actualRealItems = cart.getRealItems();
WE have defined RealItems List and getter for it. Why I cannot use it? 

P.S. 
I do not want to argue, I just do understand it. I do not understand how to system.out the products and get them after that

2021-11-01 17:20 UTC, EugenBorisik approved these changes
I recommend to follow https://www.oracle.com/technetwork/java/codeconventions-150003.pdf and avoid underscores in namings

2021-11-01 17:20 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        List<RealItem> actualRealItems = cart.getRealItems();
As I said it is done specially, this is artificial barrier. Example, how to handle System.out: https://stackoverflow.com/questions/8708342/redirect-console-output-to-string-in-java
If you have difficulties with it, you can stay it as it is, but you need to understand that such barriers will be everywhere in your work :)

2021-11-01 17:20 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        String expectedResult = "TestCart1";
```
String expectedCartName = //random generator here
Cart cart = new Cart(expectedCartName);
...
assertEquals(cart.getName(), expectedCartName);
```

2021-11-01 17:20 UTC, EugenBorisik commented on src/test/java/CartTest.java
> +        Assert.assertEquals(cart.getRealItems().size(), 1);
Please add additional assertion that total price has been changed

2021-11-01 17:20 UTC, EugenBorisik commented on src/test/java/JsonParserTests.java
> +public class JsonParserTests extends BaseSpec {
Great write/read tests!

2021-11-02 08:54 UTC, AlexandarPetsoranski commented on src/test/java/JsonParserTests.java
> +public class JsonParserTests extends BaseSpec {
THANK YOU!

2021-11-02 09:05 UTC, merged