Taks 40
AlexandarPetsoranski/SelniumTrainingRepo pull request #4
Opened 2021-11-25 19:27 UTC by AlexandarPetsoranski

In this PR: 

- All 9 tasks from [Task40.docx](https://coherentsolutions.sharepoint.com/:w:/s/training-center/EXcN6xVk3LJAv_EAkrJedKoB7KztLRadw-UMJlkFY7BVdA?e=gJlqPE) implemented
- POM applied

2021-11-26 07:04 UTC, EugenBorisik requested changes

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/yandexSpec/CreateAccount.java
> +        //Sleep is neither implicit nor explicit wait. It is way of controlling the test flow
Yes, and you must remember that usage of Thread.sleep is restricted, you can use it only if nothing helps (nothing!!!)

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/yandexSpec/CreateAccount.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
Point 4: change polling frequency

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/MultiSelectSpec.java
> +        Assertions.assertEquals(3, numberOfSelectedOptions);
You are verifying that 3 options are selected, but you also need to verify that selected options (actual) are equal to expected options (which you were selecting)

2021-11-26 07:04 UTC, EugenBorisik commented on src/main/java/pages/yandex/HomePage.java
> +    private static final By LOG_IN_BUTTON = By.xpath("//div[@class=\"HeadBanner-ButtonsWrapper\"]/a[2]");
Indexes in locators!!!

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/AlertsSpec.java
> +    private static final String PROMT_CONFIRMATION_TEXT = "You have entered 'hello' !";
Use variable HELLO_TEXT instead of 'hello'

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/WaitForLoadingElementSpec.java
> +        Assertions.assertTrue(driver.findElement(loadingDataPage.getUSER_INFORMATION()).isEnabled());
Add message on failure

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/WaitForLoadingElementSpec.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(loadingDataPage.getUSER_INFORMATION()));
Please reply to this comment: what is difference between presence and displayed?

2021-11-26 07:04 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/ProgressBarSpec.java
> +        driver.navigate().refresh();
Create custom expected condition (via implementation ExpectedCondition interface)

2021-11-26 07:04 UTC, EugenBorisik commented on src/main/java/pages/seleniumTraining/TablePage.java
> +                }
Use ternary operator

2021-11-26 07:04 UTC, EugenBorisik commented on src/main/java/pages/seleniumTraining/TablePage.java
> +                List<WebElement> columns = row.findElements(By.xpath(".//td"));
Great!!!

2021-11-26 07:37 UTC, AlexandarPetsoranski commented on src/test/java/spec/yandexSpec/CreateAccount.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
Added

2021-11-26 08:02 UTC, AlexandarPetsoranski commented on src/main/java/pages/yandex/HomePage.java
> +    private static final By LOG_IN_BUTTON = By.xpath("//div[@class=\"HeadBanner-ButtonsWrapper\"]/a[2]");
changed

2021-11-26 08:38 UTC, AlexandarPetsoranski commented on src/test/java/spec/seleniumSpec/WaitForLoadingElementSpec.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(loadingDataPage.getUSER_INFORMATION()));
isElementPresent() - This method basically tests if the element we are looking for is present somewhere in the DOM 
isDisplayed() - checks if the element is displayed and is it visible

2021-11-26 08:57 UTC, AlexandarPetsoranski commented on src/main/java/pages/seleniumTraining/TablePage.java
> +                List<WebElement> columns = row.findElements(By.xpath(".//td"));
Thank you!

2021-11-29 18:51 UTC, EugenBorisik requested changes

2021-11-29 18:51 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/MultiSelectSpec.java
> +        List<String> actualList = new ArrayList<>();
This is expected list

2021-11-29 18:51 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/MultiSelectSpec.java
> +        List<String> expectedOptions = multiSelect.getAllSelectedOptions().stream().map(WebElement::getText).collect(Collectors.toList());
This is actual options

2021-11-29 18:51 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/ProgressBarSpec.java
> +            while (isInvisible) {
Infinite loop

2021-11-30 08:35 UTC, AlexandarPetsoranski commented on src/test/java/spec/seleniumSpec/ProgressBarSpec.java
> +            while (isInvisible) {
fixed

2021-11-30 09:05 UTC, EugenBorisik requested changes

2021-11-30 09:05 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/ProgressBarSpec.java
> +            while (hasClass) {
Infinite loop. Remove

2021-12-01 06:57 UTC, EugenBorisik approved these changes

2021-12-01 06:57 UTC, EugenBorisik commented on src/test/java/spec/seleniumSpec/ProgressBarSpec.java
> +            while (hasClass) {
```
  @Test
  public void downloadTest() {
    driver.findElement(By.id("cricle-btn")).click();

    new WebDriverWait(driver, 20).until(driver -> {
      String currentPercentText = driver.findElement(By.cssSelector(".percenttext")).getText();
      int currentPercent = Integer.parseInt(currentPercentText.split("%")[0]);

      return currentPercent >= 50;
    });

    driver.navigate().refresh();
  }
```

2021-12-01 12:53 UTC, merged